### ISSUE TITLE
`res` and `num` not defined

### ISSUE THREAD

**Issue by bgailleton** [johnjarmitage/flem#2]
Hi,

I tried to output some results using the `run_flem.py` script.
The model runs normally but crashes at the output when writing the results because `num` and `res are not defined in `solve_flem.py`

I fixed it by replacing `num` by `n` (the current run number) and `res` by the input `model_space[2]`. I'll make a pull request (when I'll remember how to do so) if this is the right fix!

My version is at Commit # 03d0e31bf7ae7737d164cce46b85bd48eba8d934

Boris

**Comment by johnjarmitage** [comment]
I will fix this. I put 'res' into the array model_space[2] and 'num' can just be deleted. I will fix it now.

**Comment by johnjarmitage** [comment]
Once I get the Travis VM to work these mistakes of mine will happen less I hope. Let me know if the fix worked.

**Comment by bgailleton** [comment]
Alright thanks, I'll let you fix it! it will be easier than a pull request.
I have just realised that github as a `hub` command that makes that really easy so I shall be quicker next time!
